Move OAuth Callback logic to separate hook
Newbies-Workplace/jeteo-web pull request #20
Opened 2022-04-14 16:41 UTC by DiD3n

2022-04-14 17:26 UTC, JUtupe requested changes

2022-04-14 17:26 UTC, JUtupe commented on src/api/rest/auth/oauth/OAuthProviders.ts
> +enum OAuthProviders {
use singular form here

2022-04-14 17:26 UTC, JUtupe commented on src/contexts/auth/hooks/useGenericOAuthCallback.hook.ts
> +export const useGenericOAuthCallback = (provider: OAuthProviders): OAuthCallbackRet => {
This name would be better without the `generic` part

2022-04-15 14:04 UTC, DiD3n commented on src/api/rest/auth/oauth/OAuthProviders.ts
> +enum OAuthProviders {
👍

2022-04-15 16:46 UTC, JUtupe approved these changes

2022-04-23 09:18 UTC, JUtupe approved these changes
Next time when you add new changes after review, try to do it in another PR

2022-04-24 14:30 UTC, merged