Studio navigation
Newbies-Workplace/jeteo-web pull request #22
Opened 2022-04-16 20:56 UTC by JUtupe

2022-04-16 22:19 UTC, DiD3n requested changes

2022-04-16 22:19 UTC, DiD3n commented on src/views/studio/StudioNavButton/StudioNavButton.module.scss
> +
this css is kinda chaos
to avoid that i like to group css by its purpose
so all text, size, bg, layout related properties are close to each other

2022-04-16 22:19 UTC, DiD3n commented on src/views/studio/StudioView.tsx
> +                    </div>
nav should be in its own component
At this point it's no big deal but in future it may have more logic in it.

2022-04-16 22:19 UTC, DiD3n commented on src/views/studio/StudioView.module.scss
> +    align-items: stretch;
This 2 rules does nothing my guy

2022-04-16 22:19 UTC, DiD3n commented on src/components/ui/NavBar/NavBar.module.scss
> +    max-height: 25px;
?

2022-04-16 22:19 UTC, DiD3n commented on src/views/studio/StudioNavButton/StudioNavButton.module.scss
> +    margin-top: 15px;
margin: 7px 0;
would give better result (this css is making this weird gap between studio and nav)

2022-04-16 22:19 UTC, DiD3n commented on src/views/studio/StudioNavButton/StudioNavButton.module.scss
> +    border: medium solid #00000000;
pls use px

2022-04-24 18:27 UTC, JUtupe commented on src/components/ui/NavBar/NavBar.module.scss
> +    max-height: 25px;
I was experimenting with toolbar height, It feels less overwhelming with max height set to something like 25px (it makes big difference on screens with background color other than white)

2022-04-24 18:44 UTC, JUtupe commented on src/views/studio/StudioView.tsx
> +                    </div>
done

2022-04-24 18:45 UTC, JUtupe commented on src/views/studio/StudioNavButton/StudioNavButton.module.scss
> +
done

2022-04-25 14:45 UTC, DiD3n requested changes
Also studioView lacks padding on content section
\>This `studio` needs more personal space
![image](https://user-images.githubusercontent.com/32616724/165113481-1f99e101-5968-445e-9bc0-32d118d9a59b.png)

2022-04-25 14:45 UTC, DiD3n commented on src/components/ui/NavBar/NavBar.tsx
> +        </div></div>
\>formating

2022-04-25 14:45 UTC, DiD3n commented on src/components/ui/NavBar/NavBar.module.scss
> +    max-height: 25px;
first i thought it was leftover from experimenting
but if it's not the case then, to me 25px squeezes content too much. This rule make sense to me on mobile but not on PCs, where we can sacrifice some space to margins/padding to make app look better.

2022-04-25 14:45 UTC, DiD3n commented on src/components/ui/NavBar/NavBar.module.scss
> +    max-height: 25px;
If u still thinks navbar is too big i suggest changing padding below

2022-04-25 15:50 UTC, JUtupe commented on src/components/ui/NavBar/NavBar.module.scss
> +    max-height: 25px;
I've changed padding as you suggested

2022-04-25 15:50 UTC, JUtupe commented on src/components/ui/NavBar/NavBar.tsx
> +        </div></div>
don

2022-04-25 16:15 UTC, DiD3n approved these changes

2022-05-02 22:44 UTC, merged