Fix/event list
Newbies-Workplace/jeteo-web pull request #24
Opened 2022-06-21 22:50 UTC by DiD3n

This PR is collection of improvments more or less related to EventList component

2022-06-23 19:54 UTC, JUtupe requested changes

2022-06-23 19:54 UTC, JUtupe commented on src/components/ui/EventList/EventList.tsx
> +    size?: number
Maybe pagination should be handled inside EventList component? Is there need to handle pagination in every use of EventList?

2022-06-23 19:54 UTC, JUtupe commented on src/views/studio/StudioEventList/StudioEventList.tsx
> -                        to={`/studio/events/${event.vanityUrl}`}>
This link differs from EventList link, move it to props so it can be reusable.

2022-06-28 20:20 UTC, DiD3n commented on src/views/studio/StudioEventList/StudioEventList.tsx
> -                        to={`/studio/events/${event.vanityUrl}`}>
👍 
no :)

2022-06-28 20:20 UTC, DiD3n commented on src/views/studio/StudioEventList/StudioEventList.tsx
> -                        to={`/studio/events/${event.vanityUrl}`}>
jk, it's done mate

2022-06-29 19:15 UTC, JUtupe approved these changes

2022-06-29 20:55 UTC, merged