Tag picker
Newbies-Workplace/jeteo-web pull request #34
Opened 2022-08-06 22:35 UTC by JUtupe

2022-08-06 22:46 UTC, JUtupe commented
widzę że tu będzie jeszcze jeden bug z `Warning: validateDOMNesting(...): <form> cannot appear as a descendant of <form>.`

poprawię to na dniach

2022-08-08 16:35 UTC, DiD3n requested changes
if possible try to separate logic as well

2022-08-08 16:35 UTC, DiD3n commented on src/components/ui/TagPicker/TagPicker.tsx
> +)
move this to separate file
react is about splitting big things into small things

2022-08-08 16:35 UTC, DiD3n commented on src/components/ui/TagPicker/TagPicker.tsx
> +)
same as above

2022-08-10 17:41 UTC, JUtupe commented on src/components/ui/TagPicker/TagPicker.tsx
> +)
done

2022-08-12 07:01 UTC, merged