[WIP] Basic infrastructure
Newbies-Workplace/jeteo-web pull request #4
Opened 2021-10-13 20:17 UTC by DiD3n

some fundaments to build app on

2021-11-11 10:10 UTC, JUtupe requested changes

2021-11-11 10:10 UTC, JUtupe commented on src/common/auth/context/AuthProvider.tsx
> +        //todo(DiD3n): convince 'backend guy' to include user in response
Nice todo

~the backend guy

2021-11-11 10:10 UTC, JUtupe commented on src/common/models/ProvidersList.ts
> +enum Providers {
File name is different than enum name

2021-11-11 10:10 UTC, JUtupe commented on src/components/App.test.tsx
> +    expect(true).toBe(true);
Can you change this test to something different? Maybe test page title?

2021-11-11 10:10 UTC, JUtupe commented on src/views/auth/callback/CallbackRouter.tsx
> +
empty line

2021-11-11 10:10 UTC, JUtupe commented on src/views/auth/node.md
> +3-party OAuth provider return point
What is this flie meant for?

2021-11-11 10:10 UTC, JUtupe commented on webpack.dev.js
>      // reduce shitpost in terminal
use more appropriate comments!

2021-11-11 10:10 UTC, JUtupe commented on src/common/auth/context/AuthProvider.tsx
> +// wanna change api's ip? >> go to webpack.dev.js <<
Is there any `@see` doc keyword like in javadoc?

2021-11-24 14:10 UTC, DiD3n commented on src/common/auth/context/AuthProvider.tsx
> +// wanna change api's ip? >> go to webpack.dev.js <<
done

2021-11-24 15:33 UTC, jotceg commented on src/common/auth/context/AuthProvider.tsx
> +            createAt: 0,
Shouldn't it be "createdAt"?

2021-11-24 15:54 UTC, jotceg commented on src/common/auth/service/jwtData.interface.ts
> +    sub: string; // nickanme
Typo

2021-11-24 15:54 UTC, jotceg commented on src/common/auth/service/jwtData.interface.ts
> +    sub: string; // nickanme
rel

2021-11-24 16:20 UTC, DiD3n commented on src/common/auth/context/AuthProvider.tsx
> +        //todo(DiD3n): convince 'backend guy' to include user in response
ok?

2021-11-24 16:30 UTC, JUtupe approved these changes

2021-11-24 16:32 UTC, merged